INSERT INTO ORDER_ITEM(id, PRODUCT_CODE,PRODUCT_NAME,QUANTITY) VALUES(1,'LAP','LAPTOP',10);
INSERT INTO ORDER_ITEM(id, PRODUCT_CODE,PRODUCT_NAME,QUANTITY) VALUES(2,'MOU','MOUSE',10);
INSERT INTO ORDER_ITEM(id, PRODUCT_CODE,PRODUCT_NAME,QUANTITY) VALUES(3,'PRNT','PRINTER',10);
INSERT INTO ORDER_ITEM(id, PRODUCT_CODE,PRODUCT_NAME,QUANTITY) VALUES(4,'DVD','DVD WRITER',10);
INSERT INTO ORDER_ITEM(id, PRODUCT_CODE,PRODUCT_NAME,QUANTITY) VALUES(5,'VM','VIRTUAL MACHINE',10);
INSERT INTO ORDER_ITEM(id, PRODUCT_CODE,PRODUCT_NAME,QUANTITY) VALUES(6,'PEN','PENCIL',10);